export const technicians = [
    {
        id: 1,
        name: 'Rajesh',
        img: require("../assets/logo/pc.png"),
        rating: 5,
        price: '₹200',
        service: "Plumber",
    },
    {
        id: 2,
        name: 'Rajesh',
        img: require("../assets/logo/pc.png"),
        rating: 5,
        price: '₹200',
        service: "Plumber",
    },
    {
        id: 3,
        name: 'Rajesh',
        img: require("../assets/logo/pc.png"),
        rating: 5,
        price: '₹200',
        service: "Plumber",
    },
    {
        id: 4,
        name: 'Rajesh',
        img: require("../assets/logo/pc.png"),
        rating: 5,
        price: '₹200',
        service: "Plumber",
    },
    {
        id: 5,
        name: 'Rajesh',
        img: require("../assets/logo/pc.png"),
        rating: 5,
        price: '₹200',
        service: "Plumber",
    },
    {
        id: 6,
        name: 'Rajesh',
        img: require("../assets/logo/pc.png"),
        rating: 5,
        price: '₹200',
        service: "Plumber",
    },
    {
        id: 7,
        name: 'Rajesh',
        img: require("../assets/logo/pc.png"),
        rating: 5,
        price: '₹200',
        service: "Plumber",
    },
    {
        id: 8,
        name: 'Rajesh',
        img: require("../assets/logo/pc.png"),
        rating: 5,
        price: '₹200',
        service: "Plumber",
    },
    {
        id: 9,
        name: 'Rajesh',
        img: require("../assets/logo/pc.png"),
        rating: 5,
        price: '₹200',
        service: "Plumber",
    },
    {
        id: 10,
        name: 'Rajesh',
        img: require("../assets/logo/pc.png"),
        rating: 5,
        price: '₹200',
        service: "Plumber",
    },
    // {
    //     id: 11,
    //     name: 'Rajesh',
    //     img: require("../assets/logo/pc.png"),
    //     rating: 5,
    //     price: '₹200',
    //     service: "Plumber",
    // },
    // {
    //     id: 12,
    //     name: 'Rajesh',
    //     img: require("../assets/logo/pc.png"),
    //     rating: 5,
    //     price: '₹200',
    //     service: "Plumber",
    // },
    // {
    //     id: 13,
    //     name: 'Rajesh',
    //     img: require("../assets/logo/pc.png"),
    //     rating: 5,
    //     price: '₹200',
    //     service: "Plumber",
    // },
    // {
    //     id: 14,
    //     name: 'Rajesh',
    //     img: require("../assets/logo/pc.png"),
    //     rating: 5,
    //     price: '₹200',
    //     service: "Plumber",
    // },
    // {
    //     id: 15,
    //     name: 'Rajesh',
    //     img: require("../assets/logo/pc.png"),
    //     rating: 5,
    //     price: '₹200',
    //     service: "Plumber",
    // },
    // {
    //     id: 16,
    //     name: 'Rajesh',
    //     img: require("../assets/logo/pc.png"),
    //     rating: 5,
    //     price: '₹200',
    //     service: "Plumber",
    // },
    // {
    //     id: 17,
    //     name: 'Rajesh',
    //     img: require("../assets/logo/pc.png"),
    //     rating: 5,
    //     price: '₹200',
    //     service: "Plumber",
    // },
    // {
    //     id: 18,
    //     name: 'Rajesh',
    //     img: require("../assets/logo/pc.png"),
    //     rating: 5,
    //     price: '₹200',
    //     service: "Plumber",
    // },
    // {
    //     id: 19,
    //     name: 'Rajesh',
    //     img: require("../assets/logo/pc.png"),
    //     rating: 5,
    //     price: '₹200',
    //     service: "Plumber",
    // },
]